Update platform-upgrade to newest stable version

diff --git a/overlay/generic/usr/bin/platform-upgrade b/overlay/generic/usr/bin/platform-upgrade
--- a/overlay/generic/usr/bin/platform-upgrade
+++ b/overlay/generic/usr/bin/platform-upgrade
@@ -1,6 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# https://github.com/calmh/smartos-platform-upgrade
+# Copyright (c) 2012-2016 Jakob Borg & Contributors
+# Distributed under the MIT License
 
-host=http://builds.smartos.skylime.net
+host=https://builds.smartos.skylime.net
 latest_path=$(curl -sk "$host/latest")
 version="${latest_path##*/}"
 platform_file="platform-$version.tgz"
@@ -8,40 +11,28 @@ platform_dir="platform-$version"
 platform_url="$host$latest_path/$platform_file"
 md5sums_url="$host$latest_path/md5sums.txt"
 
+force="false"
+while getopts :f option; do
+    case "$option" in
+        f)
+            force="true"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit -1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
+IFS=_ read brand kernel < <(uname -v)
+if [[ $kernel == $version ]]; then
+    echo "Already on latest version ($kernel)."
+    $force || exit -1
+fi
+
 tmp=$(mktemp -d)
 cd "$tmp" || exit -1
-
-echo -n "Checking current boot device..."
-if [[ -z $1 ]] ; then
-        removables=($(disklist -r))
-        echo -n " detected ${removables[@]}"
-        if [[ ${#removables[@]} -gt 1 ]]; then
-                  echo
-                  echo "Error: more than one removable device detected."
-                  echo "Specify correct device on the command line."
-                  exit -1
-        fi
-        usb="/dev/dsk/${removables[0]}p1"
-else
-        usb="$1"
-        echo -n " using $usb"
-fi
-
-umount "$usb" 2>/dev/null
-mkdir usb
-if ! mount -F pcfs -o foldcase "$usb" "$tmp/usb" ; then
-        echo ", mount failed"
-        exit -1
-else
-        echo -n ", mounted"
-fi
-
-if [[ ! -d usb/platform ]] ; then
-        echo ", missing platform dir"
-        exit -1
-else
-        echo ", OK"
-fi
 
 echo -n "Downloading latest platform ($platform_file)..."
 if ! curl -sk -o "$platform_file" "$platform_url" ; then
@@ -77,6 +68,38 @@ if ! echo $version > $platform_dir/VERSION ; then
         exit -1
 else
         echo " OK"
+fi
+
+echo -n "Checking current boot device..."
+if [[ -z $1 ]] ; then
+        removables=($(disklist -r))
+        echo -n " detected ${removables[@]}"
+        if [[ ${#removables[@]} -gt 1 ]]; then
+                  echo
+                  echo "Error: more than one removable device detected."
+                  echo "Specify correct device on the command line."
+                  exit -1
+        fi
+        usb="/dev/dsk/${removables[0]}p1"
+else
+        usb="$1"
+        echo -n " using $usb"
+fi
+
+umount "$usb" 2>/dev/null
+mkdir usb
+if ! mount -F pcfs -o foldcase "$usb" "$tmp/usb" ; then
+        echo ", mount failed"
+        exit -1
+else
+        echo -n ", mounted"
+fi
+
+if [[ ! -d usb/platform ]] ; then
+        echo ", missing platform dir"
+        exit -1
+else
+        echo ", OK"
 fi
 
 echo -n "Updating platform on boot device..."
